steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/youtube-translator-backend',
      '-f', './deploy/docker/Dockerfile.prod',
      './backend'
    ]

  # Run tests (can be added later)
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['run', 'gcr.io/$PROJECT_ID/youtube-translator-backend', 'python', '-m', 'pytest']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/youtube-translator-backend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'youtube-translator-backend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/youtube-translator-backend'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'HUGGINGFACE_API_KEY=${_HUGGINGFACE_API_KEY},ENVIRONMENT=production'
    - '--memory'
    - '4Gi'
    - '--cpu'
    - '4'
    - '--min-instances'
    - '1'
    - '--max-instances'
    - '10'
    - '--concurrency'
    - '80'
    - '--timeout'
    - '300s'

images:
  - 'gcr.io/$PROJECT_ID/youtube-translator-backend'

timeout: '1800s' 