services:
  - type: web
    name: youtube-translator
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p model_cache
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: TRANSFORMERS_CACHE
        value: model_cache
    disk:
      name: model-cache
      mountPath: /opt/render/model_cache
      sizeGB: 10
