name: Deploy to GCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  BACKEND_IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/youtube-translator-backend
  FRONTEND_BUCKET: ${{ secrets.GCP_STORAGE_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup GCP authentication
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Configure Docker to use gcloud credentials
    - run: |
        gcloud auth configure-docker

    # Build and push backend
    - name: Build Backend
      run: |
        cd backend
        docker build -t ${{ env.BACKEND_IMAGE }} .
        docker push ${{ env.BACKEND_IMAGE }}

    # Deploy backend to Cloud Run
    - name: Deploy Backend
      run: |
        gcloud run deploy youtube-translator \
          --image ${{ env.BACKEND_IMAGE }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

    # Build and deploy frontend
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Deploy Frontend
      run: |
        gsutil -m cp -r frontend/build/* gs://${{ env.FRONTEND_BUCKET }}/ 